apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: learnops

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/bims-creator/learnops-ingest-api
    newTag: 0794b5570be231a3faf600e5fe3d154c6d0c3acd
  - name: ghcr.io/bims-creator/learnops-aggregator-worker
    newTag: 0794b5570be231a3faf600e5fe3d154c6d0c3acd
