apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - ingest-api.yaml
  - aggregator-worker.yaml
  - prometheus-rules.yaml

configMapGenerator:
  - name: learnops-grafana-dashboard
    files:
      - learnops-dashboard.json=dashboards/learnops-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"

labels:
  - pairs:
      app.kubernetes.io/part-of: learnops
      app.kubernetes.io/managed-by: kustomize
